spring:
    application:
        name: app-aop
    
    datasource:
        username: db
        password: db
        url: jdbc:h2:mem:testdb

    h2:
        console:
            enabled: true
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
    
